### ISSUE TITLE
running, but is there a next step ?

### ISSUE THREAD

**Issue by SAUUU** [rupansh/OpenDistortBot-rs#1]
Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/opendistortbot-rs`
^

but when i send any photo to the bot it does not procces or anything, could you help if there is a next step ?
![Screenshot_2](https://user-images.githubusercontent.com/74457926/99153116-7f354400-26b7-11eb-8a19-4881aae20bf0.png)

**Comment by rupansh** [comment]
> ```
> Finished dev [unoptimized + debuginfo] target(s) in 0.44s
>  Running `target/debug/opendistortbot-rs`
> ```
> 
> ^
> 
> but when i send any photo to the bot it does not procces or anything, could you help if there is a next step ?
> ![Screenshot_2](https://user-images.githubusercontent.com/74457926/99153116-7f354400-26b7-11eb-8a19-4881aae20bf0.png)

Send an image to the bot, reply the pic with `/distort`. Its kinda not 100% complete yet :P. 
Also you are using a debug build. run with 
`cargo run --release` for maximum performance.

**Comment by SAUUU** [comment]
> > ```
> > Finished dev [unoptimized + debuginfo] target(s) in 0.44s
> >  Running `target/debug/opendistortbot-rs`
> > ```
> > 
> > 
> > ^
> > but when i send any photo to the bot it does not procces or anything, could you help if there is a next step ?
> > ![Screenshot_2](https://user-images.githubusercontent.com/74457926/99153116-7f354400-26b7-11eb-8a19-4881aae20bf0.png)
> 
> Send an image to the bot, reply the pic with `/distort`. Its kinda not 100% complete yet :P.
> Also you are using a debug build. run with
> `cargo run --release` for maximum performance.

its worked with the `/distort` is there any chance that I can edit it so just anyone could send photos with no / ?
also, is there a way to store all photos in a file?

-- i sent you an email regards some business if you are interested reply to my email
